### ISSUE TITLE
Personas-- > roles – > sumariante (no permite agregar rol) p/ comisiones

### ISSUE THREAD

**Issue by 88lucas88** [UNPSJB/IPA#17]

**Comment by LucianoAlzugaray** [comment]
Buenas gente! les tenia una propuesta. Cambiar la forma de mostrar datos. En la lista de personas estan todas las personas independientemente de que rol ocupen, pero recien cuando entras a un listado, suponganse "directores" aparecen los directores con una lista de información distinta. Yo diria de simplificar un poco eso. De hacer que se muestre la lista de todas las personas, independiente de su rol, y en el mismo listado abajo un desplegable con los roles, y que de acuerdo a que rol se ponga se filtre la lista con las personas que tengan ese rol. Así, si se quiere ver la información de alguien , entras a ver la información de esa persona y que estén todos los datos de todos los roles, que les parece

**Comment by 88lucas88** [comment]
Es bueno el aporte, coincido en que lo hagamos así

**Comment by AndreaBageler** [comment]
ok lu, ahora quedaría sacar los botones azules
