### ISSUE TITLE
permisos/listar/Completos (cambiar tipo por tipo de uso de agua)

### ISSUE THREAD

**Issue by AndreaBageler** [UNPSJB/IPA#22]
En agregar expediente a permiso, el campo tipo - cambiar nombre

**Comment by fedectw** [comment]
Andrea ya le cambien a todos los listados de permisos el tipo -> Tipo de Uso, la parte de expediente no lo entiendi bien, si me lo cometas un poco mas lo puedo arreglar

**Comment by AndreaBageler** [comment]
Hola Fede, ya lo arreglaste. 
Cuando íbamos a los permisos con expedientes en la interfaz aparecía tipo- en vez de tipo de uso de agua.

**Comment by LucianoAlzugaray** [comment]
Si ya se arreglo cierro la issue gente
