### ISSUE TITLE
Imagen en miniatura de la documentación 

### ISSUE THREAD

**Issue by AndreaBageler** [UNPSJB/IPA#23]
No se visualiza la imagen en miniatura en permisos --> solicitudes --> detalle de la solicitud (botón i) --> ver documentación presentada

A su vez:
permisos --> solicitudes --> detalle de la solicitud (botón i) --> ver documentación presentada (cambiar nombre del botón volver a detalle del permiso, por volver a detalle de la solicitud)

**Comment by 88lucas88** [comment]
Para poder visualizar la imagen en miniatura hay que cambiar los permisos de ImageMagick.

1) Ir a sudo vim /etc/ImageMagick-6/policy.xml
2) reemplar linea:
<policy domain="coder" rights="none" pattern="PDF" />

por:
<policy domain="coder" rights="read|write" pattern="PDF" />

Además, el nombre del Boton para volver fue cambiado.
